### ISSUE TITLE
Entry ID in DiscussionAPI postDiscussionReply Function ?

### ISSUE THREAD

**Issue by 34tm4n** [instructure/CanvasAPI#337]
I am trying to post a reply on a discussion topic using this API 
/{context_id}/discussion_topics/{discussionid}/entries/{entryid}/replies
But not able to figure out what is entryid in it. Is it any field in DiscussionTopicHeader. ?

**Comment by hhoang** [comment]
hey @34tm4n, since discussions can be nested, the entry_id refers to the id of the discussion to which you are replying. Discussion responses correspond to the `DiscussionEntry` class in this library. If you are attempting to reply to just the DiscussionTopic, no entry_id is necessary, you can instead post a response to the `/{context_id}/discussion_topics/{discussionid}/entries/` endpoint. (`DiscussionAPI.postDiscussionEntry()`)
